services:
  bunsqstat:
    image: francyfox/bunsqstat:latest
    container_name: bunsqstat
    restart: unless-stopped
    ports:
      - "80:80"      # Web interface
      - "3000:3000"  # API (optional, for direct access)
      - "6379:6379"  # Redis (optional, for external access)
    environment:
      - NODE_ENV=production
      - REDIS_PASSWORD=123
      - SQUID_HOST=127.0.0.1
      - SQUID_PORT=3128
      - ACCESS_LOG=/app/logs/access.log
      - CACHE_LOG=/app/logs/cache.log
    volumes:
      - ./docker/access.log:/app/logs/access.log:ro
      - ./docker/cache.log:/app/logs/cache.log:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s