services:
  bunsqstat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bunsqstat-all-in-one
    restart: unless-stopped
    ports:
      - "81:80"      # Web interface
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
