version: '3.8'

services:
  bunsqstat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bunsqstat-all-in-one
    restart: unless-stopped
    ports:
      - "80:80"      # Web interface
      - "3000:3000"  # API (optional, for direct access)
      - "6379:6379"  # Redis (optional, for external access)
    volumes:
      - /tmp/squid/log:/app/logs:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
