name: Docker Image CI

on:
  push:
    tags: # Триггер по новым тегам
      - 'v*.*.*' # Шаблон, который будет соответствовать тегам, например, v1.0.0
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get the tag name
      id: get_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker
      run: docker build . --file Dockerfile --tag my-image-name:${{ steps.get_tag.outputs.TAG_NAME }}
    - name: Push Docker
      run: docker push my-image-name:${{ steps.get_tag.outputs.TAG_NAME }}
