name: Create Release

on:
  push:
    branches:
      - develop
#    tags:
#      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build frontend
      run: cd apps/web && bun run build

    - name: Build backend
      run: cd apps/server && bun run build

    - name: Prepare release directory
      run: |
        mkdir -p release/web
        mkdir -p release/backend
        cp -r apps/web/dist/* release/web/
        cp -r apps/server/dist/* release/backend/

    - name: Create archive
      run: tar -czf release.tar.gz release/

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          CHANGELOG.md
          LICENSE